AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  _45a14854eeba721fa8d13561c836d1199076bfc8:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      Role: "arn:aws:iam::201560601476:role/LambdaFullAccess"
      Handler: cce._45a14854eeba721fa8d13561c836d1199076bfc8::handleRequest
      MemorySize: 1024
      Timeout: 60
      CodeUri: ./target/_45a14854eeba721fa8d13561c836d1199076bfc8-1.0.0.jar
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
