# VARIABLES USED TO IDENTIFY AND CALCULATE THE COST TO PROCESS A DEVICE RULES.

# Category/Manufacturer and Device Name (It will form a unique identifier for this device).
devname: webserver.php

# Events per second (average).
eps: 719

# Number of verifications associated to this device.
ver: 52

# Percentage of DB inserts according to the number of EPS (average).
ins: 10.3

# These four values are calculated using power regression and used to estimate the cost value.
epsR: 0.42
verR: 0.345
insR: 0.398
conR: 1.645

# Estimated cost (in milliseconds) to process the set of values for this device (eps, ver, ins).
cost: 564

# Bin ID associated to this device. It is used to identify the group (lambda) this device belongs to.
bin: _f1a3f0221cc855d42cadbf65b50ab3dd6d3ff263