AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ${className}:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      Role: "arn:aws:iam::<your_account_id>:role/LambdaFullAccess"
      Handler: ${package}.${className}::handleRequest
      MemorySize: 1024
      Timeout: 60
      CodeUri: ./target/${className}-${version}.jar
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
