# VARIABLES USED TO IDENTIFY AND CALCULATE THE COST TO PROCESS A DEVICE RULES.

# Category/Manufacturer and Device Name (It will form a unique identifier for this device).
devname: sgbd.mysql

# Events per second (average).
eps: 856

# Number of verifications associated to this device.
ver: 34

# Percentage of DB inserts according to the number of EPS (average).
ins: 6.6

# These four values are calculated using power regression and used to estimate the cost value.
epsR: 0.42
verR: 0.345
insR: 0.398
conR: 1.496

# Estimated cost (in milliseconds) to process the set of values for this device (eps, ver, ins).
cost: 427

# Bin ID associated to this device. It is used to identify the group (lambda) this device belongs to.
bin: _45a14854eeba721fa8d13561c836d1199076bfc8