AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  correlation:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      Role: "arn:aws:iam::201560601476:role/LambdaFullAccess"
      Handler: cce.correlation::handleRequest
      MemorySize: 1024
      Timeout: 60
      CodeUri: ./target/correlation-1.0.0.jar
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
