AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  _f1a3f0221cc855d42cadbf65b50ab3dd6d3ff263:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Role: arn:aws:iam::201560601476:role/LambdaFullAccess
      Handler: cce._f1a3f0221cc855d42cadbf65b50ab3dd6d3ff263::handleRequest
      MemorySize: 1024
      Timeout: 60
      CodeUri: s3://cce-bucket/_f1a3f0221cc855d42cadbf65b50ab3dd6d3ff263/18674073cbf67def54a74667502534d6
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
