AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  _45a14854eeba721fa8d13561c836d1199076bfc8:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Role: arn:aws:iam::201560601476:role/LambdaFullAccess
      Handler: cce._45a14854eeba721fa8d13561c836d1199076bfc8::handleRequest
      MemorySize: 1024
      Timeout: 60
      CodeUri: s3://cce-bucket/_45a14854eeba721fa8d13561c836d1199076bfc8/1579bb2a895b060c132121d23fcb4e8c
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
