# VARIABLES USED TO IDENTIFY AND CALCULATE THE COST TO PROCESS A DEVICE RULES.

# Category/Manufacturer and Device Name (It will form a unique identifier for this device).
devname: sgbd.postgresql

# Events per second (average).
eps: 749

# Number of verifications associated to this device.
ver: 26

# Percentage of DB inserts according to the number of EPS (average).
ins: 5.1

# These four values are calculated using power regression and used to estimate the cost value.
epsR: 0.42
verR: 0.345
insR: 0.398
conR: 1.645

# Estimated cost (in milliseconds) to process the set of values for this device (eps, ver, ins).
cost: 347

# Bin ID associated to this device. It is used to identify the group (lambda) this device belongs to.
bin: _363cfc2da4d8ba4d87d38fdc678cb7c96f0ef12d